#!/usr/bin/env python3
"""Analyze the permutation group generated by a Moore restricted certificate.

This is diagnostic only: it does not prove anything about all possible certificates.
For a supplied solver-independent certificate it records parity, transitivity, and the
exact generated group order computed by SymPy's Schreier-Sims implementation.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

from sympy.combinatorics import Permutation, PermutationGroup


def permutation_sign(arr: list[int]) -> int:
    seen = [False] * len(arr)
    cycles = 0
    for i in range(len(arr)):
        if seen[i]:
            continue
        cycles += 1
        j = i
        while not seen[j]:
            seen[j] = True
            j = arr[j]
    return -1 if (len(arr) - cycles) % 2 else 1


def analyze(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    n = int(data["n_symbols"])
    sol = data["solution"]
    arrays = [[int(x) for x in sol[k]] for k in sorted(sol)]
    signs = [permutation_sign(a) for a in arrays]
    gens = [Permutation(a, size=n) for a in arrays]
    group = PermutationGroup(gens)
    order = int(group.order())
    alt_order = math.factorial(n) // 2
    return {
        "certificate": str(path),
        "n_symbols": n,
        "generators": len(gens),
        "all_generators_even": all(s == 1 for s in signs),
        "odd_generator_count": sum(s == -1 for s in signs),
        "transitive": bool(group.is_transitive()),
        "generated_group_order": str(order),
        "alternating_group_order": str(alt_order),
        "generates_A_n": order == alt_order and all(s == 1 for s in signs),
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("certificate", type=Path)
    ap.add_argument("--output", type=Path)
    args = ap.parse_args()
    result = analyze(args.certificate)
    text = json.dumps(result, indent=2, sort_keys=True)
    print(text)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
